import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { R2Client } from "./r2";

/**
 * Where uploaded bytes live.
 *
 * Production is R2. Until 0005 every attachment was written to /tmp inside the
 * container, so each redeploy silently deleted every file anyone had attached
 * while the database kept pointing at them. Local disk is still offered, but
 * ONLY outside production: a production boot with no R2 configured throws on
 * the first upload instead of quietly repeating that mistake.
 *
 *   R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET
 *   R2_PREFIX   optional, default "pm/" — lets Projects share a bucket with
 *               another app without the two ever naming the same key
 */
export interface ObjectStore {
  readonly kind: "r2" | "disk";
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
  /** A URL the browser can fetch the object from for a short while, or null to stream it ourselves. */
  signedUrl(key: string, opts: { ttlSeconds: number; downloadName?: string; inline?: boolean; contentType?: string }): string | null;
}

export class StorageNotConfiguredError extends Error {
  constructor() {
    super("Object storage is not configured (R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY / R2_BUCKET)");
  }
}

function prefix(): string {
  const p = process.env.R2_PREFIX ?? "pm/";
  return p && !p.endsWith("/") ? `${p}/` : p;
}

class R2Store implements ObjectStore {
  readonly kind = "r2" as const;
  constructor(private readonly client: R2Client) {}
  put(key: string, body: Uint8Array, contentType: string) { return this.client.put(prefix() + key, body, contentType); }
  get(key: string) { return this.client.get(prefix() + key); }
  delete(key: string) { return this.client.delete(prefix() + key); }
  signedUrl(key: string, opts: { ttlSeconds: number; downloadName?: string; inline?: boolean; contentType?: string }) {
    const extra: Record<string, string> = {};
    const name = (opts.downloadName ?? "").replace(/["\r\n\\]/g, "");
    extra["response-content-disposition"] = `${opts.inline ? "inline" : "attachment"}${name ? `; filename="${name}"` : ""}`;
    if (opts.contentType) extra["response-content-type"] = opts.contentType;
    return this.client.presign("GET", prefix() + key, opts.ttlSeconds, extra);
  }
}

/** Development only. Keys are generated by us, but resolve defensively anyway. */
class DiskStore implements ObjectStore {
  readonly kind = "disk" as const;
  private readonly root = path.resolve(process.cwd(), ".data/uploads");
  private resolve(key: string): string {
    const full = path.resolve(this.root, key);
    if (!full.startsWith(this.root + path.sep)) throw new Error("Invalid storage key");
    return full;
  }
  async put(key: string, body: Uint8Array) {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, body);
  }
  async get(key: string) {
    try { return new Uint8Array(await readFile(this.resolve(key))); } catch { return null; }
  }
  async delete(key: string) { await rm(this.resolve(key), { force: true }); }
  signedUrl() { return null; }
}

let cached: ObjectStore | null = null;

export function storage(): ObjectStore {
  if (cached) return cached;
  const { R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET, R2_ENDPOINT } = process.env;
  if (R2_ACCOUNT_ID && R2_ACCESS_KEY_ID && R2_SECRET_ACCESS_KEY && R2_BUCKET) {
    cached = new R2Store(new R2Client({
      accountId: R2_ACCOUNT_ID,
      accessKeyId: R2_ACCESS_KEY_ID,
      secretAccessKey: R2_SECRET_ACCESS_KEY,
      bucket: R2_BUCKET,
      endpoint: R2_ENDPOINT || undefined,
    }));
  } else if (process.env.NODE_ENV !== "production") {
    cached = new DiskStore();
  } else {
    throw new StorageNotConfiguredError();
  }
  return cached;
}

/**
 * `<orgId>/<area>/<owner>/<random>-<name>`. The org leads so a bucket listing
 * (or a lifecycle rule, or a deletion on offboarding) can be done per tenant.
 * The random segment means two files with the same name never overwrite each
 * other — the old /tmp scheme did exactly that.
 */
export function newStorageKey(orgId: string, area: string, owner: string, filename: string): string {
  const clean = safeFilename(filename);
  const seg = (s: string) => s.replace(/[^a-zA-Z0-9_-]/g, "_");
  return `${seg(orgId)}/${seg(area)}/${seg(owner)}/${crypto.randomBytes(8).toString("hex")}-${clean}`;
}

export function safeFilename(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9._-]/g, "_").replace(/^\.+/, "_").slice(-120);
  return cleaned || "file";
}

/** Image types browsers render inline safely. SVG is deliberately absent: it can carry script. */
export const INLINE_IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp", "image/gif", "image/heic", "image/heif"]);
